AppPage/urls.py
from django.urls import path
from . import views

app_name = 'AppPage'
urlpatterns = [
    path("", views.index , name="index"),
    path("add", views.add , name='add'),
]

PhoneStore/urls.py
from django.urls import path
from . import views

app_name = 'PhoneStore'
urlpatterns = [
    path("", views.index, name="index"),
    path("add", views.add, name='add'),
    # path("<int:phone_id>", views.phone, name='phone_list'),
    path("list", views.phone, name='phone'),

    path('logina', views.logina, name='login'),
    path('register', views.register, name="register"),
    path('addProduct', views.viewaddform, name='viewaddform')

]

Project424/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('PhoneStore/' , include('PhoneStore.urls')),
    path('AppPage/' , include('AppPage.urls'))
]

AppPage/models.py
from django.db import models

# Create your models here.

PhoneStore/models.py
from django.db import models


class Phone(models.Model):
    name = models.CharField(max_length=100)
    manufacturer = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    description = models.TextField()
    image = models.ImageField(
       upload_to='https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-14-pro-max-1.jpg')

    def str(self):
        return f"{self.name} {self.price} {self.manufacturer} {self.description}"

PhoneStore/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class SignUpForm(UserCreationForm):
    email = forms.EmailField(label='Email')
    first_name = forms.CharField(label='First Name')
    last_name = forms.CharField(label='Last Name')
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', 'first_name', 'last_name')

AppPage/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django import forms
from django.urls import reverse
from django.http import HttpResponseRedirect

# Create your views here.

class NewItemForm(forms.Form):
    item = forms.IntegerField(label='Number of items')

def index(request):
    
    if "AppPage" not in request.session:

        request.session["AppPage"] = []

    return render(request, "AppPage/index.html" , {"AppPage": request.session["AppPage"]})

def add(request):
    if request.method == "POST":
        form=NewItemForm(request.POST)

        if form.is_valid():

            item=form.cleaned_data["item"]

            request.session["AppPage"]+=[item]

            return HttpResponseRedirect(reverse("AppPage:index"))
        else:
            return render(request, "AppPage/add.html" , {})
        
    return render(request, "AppPage/add.html" , {"form": NewItemForm()})

PhoneStore/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django import forms
from django.urls import reverse
from django.http import HttpResponseRedirect
from .models import Phone
from PhoneStore.forms import SignUpForm


def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            return reverse()
    else:
        form = SignUpForm()

    return render(request, 'PhoneStore/register.html', {'form': form})


def logina(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            # replace 'home'with the name of your home page URL pattern
            return redirect('home')
        else:
            # handle invalid login credentials
            pass
    else:
        return render(request, 'PhoneStore/login.html')


def phone(request):
    return render(request, 'PhoneStore/allProducts.html', {
        'phone': Phone.objects.all()
    })


class NewItemForm(forms.Form):
    item = forms.IntegerField(label='Number of items')


def index(request):

    if "PhoneStore" not in request.session:

        request.session["PhoneStore"] = []

    return render(request, "PhoneStore/index.html", {"PhoneStore": request.session["PhoneStore"]})


def add(request):
    if request.method == "POST":
        form = NewItemForm(request.POST)

        if form.is_valid():

            item = form.cleaned_data["item"]

            request.session["PhoneStore"] += [item]

            return HttpResponseRedirect(reverse("PhoneStore:index"))
        else:
            return render(request, "PhoneStore/specificProduct.html", {})

    return render(request, "PhoneStore/specificProduct.html", {"form": NewItemForm()})

# user add new product


class uaddproductForm(forms.ModelForm):
    class Meta:
        model = Phone
        # fields = ['name', 'manufacturer', 'price', 'description']
        fields = "__all__"


def viewaddform(request):
    if request.method == 'POST':
        form = uaddproductForm(request.POST)
        if (form.is_valid()):
            form.save()

    else:
        form = uaddproductForm()

    return render(request, "PhoneStore/userAddP.html",
                  {"form": uaddproductForm()})
#

AppPage/templates/AppPage/add.html
 {% extends 'AppPage/layout.html' %}

{% block body%}
<img src="https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-14-pro-max-1.jpg" alt="item picture" width="250px">
        <form action="{% url 'AppPage:add' %}" method="post">
             {% csrf_token %}
            {{ form }}
            <input type="submit">
        </form>
        <p>
            ابل ايفون 14 برو ماكس
            <br>
            السعة : 128 جيجابايت
            <br>
            مقاس الشاشة : 6.7 بوصة
            <br>
            مميزات الكاميرا الخاصة : ثبات صورةبصري مزدوج 2X فاصل زمني للوضع الليلي ، تقريب بصري        
        
        </p>
{% endblock %}
    </html>

AppPage/templates/AppPage/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title> Hello </title>
    </head>
    <body>
        <h1> Hello, World </h1>
    </body>
    </html>

AppPage/templates/AppPage/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title> Add item </title>
    </head>
    <body>
         {% block body%}
        {% endblock %}
    </body>
    </html>

PhoneStore/templates/PhoneStore/allProducts.html
{% extends "PhoneStore/layout.html" %}


{% block body %}
<h1>phones</h1>

<style>
  
</style>
<table>
    <tr>
        <th>name</th>
        <th>manufacturer</th>
        <th>price</th>
        <th>description</th>
        {% for p in phone %}
        <tr>
            <td>{{p.name}}</td>
            <td>{{p.manufacturer}}</td>
            <td>{{p.price}}</td>
            <td>{{p.description}}</td>
            {% endfor %}
        </tr>
    </tr>
</table>

{% endblock %}

PhoneStore/templates/PhoneStore/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title> Hello </title>
    </head>
    <body>
        <h1> Hello, World </h1>
    </body>
    </html>

PhoneStore/templates/PhoneStore/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Add item</title>
  </head>
  <body>
    {% block body%} {% endblock %}
  </body>
</html>

PhoneStore/templates/PhoneStore/login.html
<!DOCTYPE html >

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>login</title>

</head>


<body>

  {% block content %}
    <h1 align = 'center'>Login</h1>

    <form method="post" align = 'center'>
      {% csrf_token %}
      <div>
        <label for="username">Username:</label>
        <input type="text" name="username" placeholder="Username" required>
      </div>
      <br>
      <div>
        <label for="password">Password:</label>
        <input type="password" name="password" placeholder="Password" required>
      </div>
      <br>
      <button type="submit">Login</button>

  <hr>
      <p>Don't have an account click here </p>
    </form>
{% endblock %}
</body>
</html>

PhoneStore/templates/PhoneStore/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Register</title>
    <style>
      .signup-form {
    width: 500px;
    margin: 0 auto;
}

.signup-form input {
    width: 100%;
}

.signup-form button {
    margin-top: 10px;
}
    </style>
</head>
<body>
{% block content %}


<form action="{% url 'PhoneStore:register' %}" method="post" class="signup-form">
    {% csrf_token %}

    {{ form.username.label }}
    {{ form.username }}
    <br>
    {{ form.email.label }}
    {{ form.email }}
    <br>
    {{ form.first_name.label }}
    {{ form.first_name }}
    <br>

    {{ form.last_name.label }}
    {{ form.last_name }}
    <br>
    {{ form.password1.label }}
    {{ form.password1 }}
    <br>
    {{ form.password2.label }}
    {{ form.password2 }}
    <input type="submit" value="Sign Up">
</form>
{% endblock %}
</form>
</body>
</html>

PhoneStore/templates/PhoneStore/specificProduct.html
{% extends 'PhoneStore/layout.html' %}

{% block body%}
<img src="https://fdn2.gsmarena.com/vv/pics/apple/apple-iphone-14-pro-max-1.jpg" alt="item picture" width="250px">
        <form action="{% url 'PhoneStore:add' %}" method="post">
             {% csrf_token %}
            {{ form }}
            <input type="submit">
        </form>
        <p>
            ابل ايفون 14 برو ماكس
            <br>
            السعة : 128 جيجابايت
            <br>
            مقاس الشاشة : 6.7 بوصة
            <br>
            مميزات الكاميرا الخاصة : ثبات صورةبصري مزدوج 2X فاصل زمني للوضع الليلي ، تقريب بصري        
        
        </p>
{% endblock %}
    </html>

PhoneStore/templates/PhoneStore/userAddP.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>add new product</title>
    <style>
      body {
        text-align: center;
      }
      form {
        display: inline-block;
      }
    </style>
  </head>
  <body>
    <form
      action="{% url 'PhoneStore:viewaddform'%}"
      method="post"
      class="viewaddform"
    >
      {% csrf_token %} {{form.name.label}} {{form.name}}
      <br />
      {{form.manufacturer.label}} {{form.manufacturer}}
      <br />
      {{form.price.label}} {{form.price}}
      <br />
      {{form.description.label}} {{form.description}}
      <br />
      <input type="submit" value="submit" />
    </form>
  </body>
</html>